//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Id { get; set; }
        public int DeliverId { get; set; }
        public int FromLocId { get; set; }
        public int ToLocId { get; set; }
    
        public virtual tblDelivery tblDelivery { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblLocation tblLocation1 { get; set; }
    }
}
