//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblBuyer
    {
        public tblBuyer()
        {
            this.tblDeliveries = new HashSet<tblDelivery>();
            this.tblPayments = new HashSet<tblPayment>();
        }
        [Key]
        public int BuyerId { get; set; }
        [Required(ErrorMessage="Buyer First Name is required")]
        [StringLength(30, MinimumLength=2)]
        public string FName { get; set; }
        [StringLength(30)]
        public string MName { get; set; }
        [StringLength(30)]
        [Required(ErrorMessage = "Buyer Last Name is required")]
        public string LName { get; set; }
        public bool Verified { get; set; }
        public int LocationId { get; set; }
        public int UserId { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblLogin tblLogin { get; set; }
        public virtual ICollection<tblDelivery> tblDeliveries { get; set; }
        public virtual ICollection<tblPayment> tblPayments { get; set; }
    }
}
