//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelivery
    {
        public tblDelivery()
        {
            this.Shipments = new HashSet<Shipment>();
        }
        
        public int DeliverId { get; set; }
        public string Medium { get; set; }
        public Nullable<int> TrackingNo { get; set; }
        public string Status { get; set; }
        public int ProductId { get; set; }
        public int BuyerId { get; set; }
    
        public virtual ICollection<Shipment> Shipments { get; set; }
        public virtual tblBuyer tblBuyer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
