//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public tblLogin()
        {
            this.tblBuyers = new HashSet<tblBuyer>();
            this.tblSellers = new HashSet<tblSeller>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Access { get; set; }
        public bool Lock { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
    
        public virtual ICollection<tblBuyer> tblBuyers { get; set; }
        public virtual ICollection<tblSeller> tblSellers { get; set; }
    }
}
