//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblLocation
    {
        public tblLocation()
        {
            this.Shipments = new HashSet<Shipment>();
            //this.Shipments1 = new HashSet<Shipment>();
            this.tblBuyers = new HashSet<tblBuyer>();
            this.tblSellers = new HashSet<tblSeller>();
        }
        [Key]
        public int LocationId { get; set; }
        [Required(ErrorMessage="Address is Required")]
        [StringLength(300)]
        public string Address { get; set; }
        [Required(ErrorMessage = "City is Required")]
        [StringLength(50)]
        public string City { get; set; }
        [Required(ErrorMessage="Please enter the State from the List")]
        public string State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<int> Phone { get; set; }
        [Required(ErrorMessage="Please enter your email address")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email Address")]
        [MaxLength(50)]
        [EmailAddress]
        //[RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2-4}",ErrorMessage="Please enter correct email address")]
        public string Email { get; set; }
        [DisplayName("Facebook Username")]
        [MaxLength(50)]
        public string Facebook { get; set; }
    
        public virtual ICollection<Shipment> Shipments { get; set; }
        public virtual ICollection<Shipment> Shipments1 { get; set; }
        public virtual ICollection<tblBuyer> tblBuyers { get; set; }
        public virtual ICollection<tblSeller> tblSellers { get; set; }
    }
}
