//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public tblPayment()
        {
            this.tblTransactions = new HashSet<tblTransaction>();
        }
    
        public int PaymentId { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> RemAmount { get; set; }
        public bool PaidStatus { get; set; }
        public int TransactionId { get; set; }
        public int BuyerId { get; set; }
    
        public virtual tblBuyer tblBuyer { get; set; }
        public virtual ICollection<tblTransaction> tblTransactions { get; set; }
    }
}
