//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblDeliveries = new HashSet<tblDelivery>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Amount { get; set; }
        public string Comment { get; set; }
        public int SellerId { get; set; }
    
        public virtual ICollection<tblDelivery> tblDeliveries { get; set; }
        public virtual tblSeller tblSeller { get; set; }
    }
}
